### ISSUE TITLE
Crash on dedicated server when OP uses /homes

### ISSUE THREAD

**Issue by dandin87** [gdude2002/FabriKommander#3]
AoF3 2.4.1 Modpack NA public server. I think it might be related to having having a home in a non vanilla dimension, as I tested the commands out on a test server before we added it. I used ot be able to use /homes, but after I set homes in Astromine dimensions using the /homes command crashes the server. I think even entering my own name after homes crashes the server, I can test this more later tongiht. But here is the log.

[23:11:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: java.util.Optional.isEmpty()Z
	at me.gserv.fabrikommander.utils.ObjectsKt.identifierToWorldName(ObjectsKt.java:14) ~[FabriKommander-1.0.0-MC1.16.3.jar:?]
	at me.gserv.fabrikommander.commands.HomesCommand.homesCommand(HomesCommand.java:78) ~[FabriKommander-1.0.0-MC1.16.3.jar:?]
	at me.gserv.fabrikommander.commands.HomesCommand$register$1.run(HomesCommand.java:18) ~[FabriKommander-1.0.0-MC1.16.3.jar:?]

https://hastebin.com/piboqewegi.yaml

**Comment by gdude2002** [comment]
Hmm, that's an interesting one. What version and distribution of Java are you using?

**Comment by dandin87** [comment]
Java 8
Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 5.8.0-28-generic
	Java Version: 1.8.0_275, Private Build  
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 8516627104 bytes (8122 MB) / 15032385536 bytes (14336 MB) up to 30064771072 bytes (28672 MB)
	CPUs: 12

Crashlog, I forgot thats where some more info is.
https://hastebin.com/apiwifiweh.yaml

**Comment by gdude2002** [comment]
Hmm, okay. I believe the root cause of the crash is this:

`java.lang.NoSuchMethodError: java.util.Optional.isEmpty()Z`

This suggests to me a different in JRE/JDK, but alas I'm really not sure where it might be.

I'm going to have to get back to you on this one, unfortunately

**Comment by dandin87** [comment]
I will upload the homes data to our test server and play with replicating different scenarios or even different java versions. We know not to use /homes and I don't think it affects non OPs oddly. I'm also pretty sure I can do /homes otherplayersname and it works fine I think, but I haven't really played with it since the sever usually has a 5-15 ppl on all the time. The mod does its main purpose which is letting players tp to homes, which while we were using Gunpowder became an issue since it was resetting homes on server restart. 

Any plans on adding the other commands like tpa, rpt etc?

**Comment by gdude2002** [comment]
It's definitely an issue referring to modded dimensions — I think I can probably patch it and get a release out, I've had an idea.

Yes, I'd like to add more things — at the moment I'm a bit busy, since I'm a moderator on the Fabric Discord server, but I'll get there.

**Comment by gdude2002** [comment]
Could you give this version a go?

[FabriKommander-1.0.0-MC1.16.4.zip](https://github.com/gdude2002/FabriKommander/files/5559629/FabriKommander-1.0.0-MC1.16.4.zip)

(It's a zip containing a JAR)

**Comment by gdude2002** [comment]
@dandin87 Have you had a chance to try that?

**Comment by dandin87** [comment]
Sorry, did see a notification. I'll be adding it the server tonight and test it out. Thanks.

**Comment by dandin87** [comment]
Looks like its fixed! thanks.

**Comment by gdude2002** [comment]
No worries — I can't get a release out right now, but since it's on the server you can feel free to keep using that copy
